const TelegramBot = require('node-telegram-bot-api').default || require('node-telegram-bot-api');
const axios = require('axios');
const fs = require('fs');

const TELEGRAM_TOKEN = '8417783415:AAF5d1xXD_2rrA3Knec_OSwtnXD5iEgl9GU';

const API_USER = '1436050434';
const API_SECRET = 'NRmfxmKyEyJoQrJsLpesncpboDTquxxf';

const ADMIN_ID = 8419615333; 
const LOG_CHANNEL_ID = -1004312367012; 

const bot = new TelegramBot(TELEGRAM_TOKEN, { polling: true });

const messages = {
  uz: {
    analyzing: "🔍 Rasm tahlil qilinmoqda, kuting...",
    title: "FactLens Rasm Tahlil Natijasi:",
    aiProb: "AI (Sun'iy intellekt) ehtimoli:",
    summaryReal: "✅ Xulosa: Rasm original va haqiqiy fotosuratga o'xshaydi.",
    summaryAI: "⚠️ Xulosa: Rasm AI tomonidan yaratilgan bo'lishi ehtimoli yuqori."
  },
  en: {
    analyzing: "🔍 Analyzing image, please wait...",
    title: "FactLens Image Analysis Result:",
    aiProb: "AI probability:",
    summaryReal: "✅ Conclusion: The image appears to be authentic and original.",
    summaryAI: "⚠️ Conclusion: High probability that the image was generated by AI."
  }
};

const USER_LANGS_FILE = './user_languages.json';

function getUserLanguages() {
  if (!fs.existsSync(USER_LANGS_FILE)) {
    fs.writeFileSync(USER_LANGS_FILE, JSON.stringify({}));
  }
  try {
    const data = fs.readFileSync(USER_LANGS_FILE);
    return JSON.parse(data);
  } catch (e) {
    return {};
  }
}

function setUserLanguage(userId, lang) {
  const langs = getUserLanguages();
  langs[userId] = lang;
  fs.writeFileSync(USER_LANGS_FILE, JSON.stringify(langs, null, 2));
}

function getUserLanguage(userId) {
  const langs = getUserLanguages();
  return langs[userId] || 'uz';
}

const USERS_FILE = './users.json';
function getUsers() {
  if (!fs.existsSync(USERS_FILE)) {
    fs.writeFileSync(USERS_FILE, JSON.stringify([]));
  }
  try {
    const data = fs.readFileSync(USERS_FILE);
    return JSON.parse(data);
  } catch (e) {
    return [];
  }
}

function saveUser(user) {
  if (!user) return;
  const users = getUsers();
  const exists = users.find(u => u.id === user.id);
  if (!exists) {
    users.push({
      id: user.id,
      first_name: user.first_name || '',
      last_name: user.last_name || '',
      username: user.username ? `@${user.username}` : 'Mavjud emas',
      date: new Date().toISOString().split('T')[0]
    });
    fs.writeFileSync(USERS_FILE, JSON.stringify(users, null, 2));
  }
}

async function logToAdmin(msg, fileType, aiScore, resultMessage) {
  try {
    const targetId = (LOG_CHANNEL_ID && LOG_CHANNEL_ID !== -1002345678910) ? LOG_CHANNEL_ID : ADMIN_ID;
    const user = msg.from;
    const userInfo = `👤 <b>Foydalanuvchi:</b> ${user.first_name || ''} ${user.last_name || ''} (${user.username ? '@' + user.username : 'Username yo\'q'})\n🆔 <b>ID:</b> <code>${user.id}</code>\n📂 <b>Tur:</b> ${fileType}\n📊 <b>AI Natijasi:</b> ${aiScore}%`;

    if (fileType === 'Rasm') {
      const fileId = msg.photo[msg.photo.length - 1].file_id;
      await bot.sendPhoto(targetId, fileId, { caption: userInfo, parse_mode: 'HTML' });
    } else if (fileType === 'Video') {
      const fileId = msg.video.file_id;
      await bot.sendVideo(targetId, fileId, { caption: userInfo, parse_mode: 'HTML' });
    }
  } catch (err) {
    console.error('Log yuborishda xatolik:', err.message);
  }
}

bot.onText(/\/start/, (msg) => {
  saveUser(msg.from);
  const chatId = msg.chat.id;

  const options = {
    reply_markup: {
      inline_keyboard: [
        [
          { text: "🇺🇿 O'zbekcha", callback_data: "lang_uz" },
          { text: "🇬🇧 English", callback_data: "lang_en" }
        ]
      ]
    }
  };

  bot.sendMessage(chatId, "Iltimos, tilni tanlang / Please select a language:", options);
});

bot.on('callback_query', async (query) => {
  const chatId = query.message.chat.id;
  const userId = query.from.id;
  const data = query.data;

  if (data === 'lang_uz') {
    setUserLanguage(userId, 'uz');
    await bot.answerCallbackQuery(query.id, { text: "🇺🇿 O'zbek tili tanlandi!" });
    
    try { await bot.deleteMessage(chatId, query.message.message_id); } catch (e) {}

    bot.sendMessage(
      chatId, 
      "👋 Salom! Men *FactLens AI* botiman.\n\nMenga har qanday *rasm* yoki *video* yuboring, men uning *AI* orqali yaratilganini yoki haqiqiyligini tahlil qilaman.",
      { parse_mode: 'Markdown' }
    );
  } else if (data === 'lang_en') {
    setUserLanguage(userId, 'en');
    await bot.answerCallbackQuery(query.id, { text: "🇬🇧 English selected!" });

    try { await bot.deleteMessage(chatId, query.message.message_id); } catch (e) {}

    bot.sendMessage(
      chatId, 
      "👋 Hello! I am *FactLens AI* bot.\n\nSend me any *image* or *video*, and I will analyze whether it is created by *AI* or authentic.",
      { parse_mode: 'Markdown' }
    );
  }
});

bot.onText(/\/users/, (msg) => {
  saveUser(msg.from);
  const chatId = msg.chat.id;

  if (chatId !== ADMIN_ID) {
    return bot.sendMessage(chatId, "⚠️ Bu buyruq faqat bot admini uchun!").catch(console.error);
  }

  const users = getUsers();
  if (users.length === 0) {
    return bot.sendMessage(chatId, "Hali hech kim botdan foydalanmadi.").catch(console.error);
  }

  let text = `👥 <b>Bot foydalanuvchilari soni:</b> ${users.length} ta\n\n`;
  users.forEach((u, index) => {
    const safeFirstName = (u.first_name || '').replace(/</g, "&lt;").replace(/>/g, "&gt;");
    const safeLastName = (u.last_name || '').replace(/</g, "&lt;").replace(/>/g, "&gt;");
    const safeUsername = (u.username || '').replace(/</g, "&lt;").replace(/>/g, "&gt;");

    text += `${index + 1}. ${safeFirstName} ${safeLastName} (${safeUsername}) - ID: <code>${u.id}</code>\n`;
  });

  bot.sendMessage(chatId, text, { parse_mode: 'HTML' }).catch(console.error);
});

bot.on('message', (msg) => {
  saveUser(msg.from);
  const chatId = msg.chat.id;

  console.log("➡️ Kelgan xabar Chat ID-si:", chatId);

  if (!msg.photo && !msg.video && msg.text && !msg.text.startsWith('/')) {
    if (msg.chat.type === 'private') {
      bot.sendMessage(chatId, '⚠️ Iltimos, tahlil qilish uchun **rasm** yoki **video** yuboring!', { parse_mode: 'Markdown' }).catch(console.error);
    }
  }
});

bot.on('photo', async (msg) => {
  saveUser(msg.from);
  const chatId = msg.chat.id;

  const lang = getUserLanguage(msg.from.id);
  const text = messages[lang];

  bot.sendMessage(chatId, text.analyzing).catch(console.error);

  try {
    const fileId = msg.photo[msg.photo.length - 1].file_id;
    const fileUrl = await bot.getFileLink(fileId);

    const response = await axios.get('https://api.sightengine.com/1.0/check.json', {
      params: {
        'url': fileUrl,
        'models': 'genai',
        'api_user': API_USER,
        'api_secret': API_SECRET
      }
    });

    const aiScore = Math.round(response.data.type.ai_generated * 100);

    const summary = aiScore > 60 ? text.summaryAI : text.summaryReal;
    const resultMessage = `📊 **${text.title}**\n\n🤖 ${text.aiProb} **${aiScore}%**\n\n${summary}`;

    await bot.sendMessage(chatId, resultMessage, { parse_mode: 'Markdown' }).catch(console.error);

    logToAdmin(msg, 'Rasm', aiScore, resultMessage);

  } catch (error) {
    console.error('Rasm tahlilida xatolik:', error);
    const errText = lang === 'en' 
      ? '❌ Sorry, an error occurred while analyzing the image.' 
      : '❌ Kechirasiz, rasmni tahlil qilishda xatolik yuz berdi.';
    bot.sendMessage(chatId, errText).catch(console.error);
  }
});

bot.on('video', async (msg) => {
  saveUser(msg.from);
  const chatId = msg.chat.id;

  const lang = getUserLanguage(msg.from.id);
  const text = messages[lang];

  if (msg.video.file_size > 20 * 1024 * 1024) {
    const sizeText = lang === 'en' 
      ? '⚠️ Video file size must not exceed 20 MB!' 
      : '⚠️ Video hajmi 20 MB dan oshmasligi kerak!';
    return bot.sendMessage(chatId, sizeText).catch(console.error);
  }

  const waitVideoText = lang === 'en' 
    ? '🎥 Analyzing video, please wait...' 
    : '🎥 Video tahlil qilinmoqda, kuting...';
  bot.sendMessage(chatId, waitVideoText).catch(console.error);

  try {
    let fileId = msg.video.thumbnail ? msg.video.thumbnail.file_id : msg.video.file_id;
    const fileUrl = await bot.getFileLink(fileId);

    const response = await axios.get('https://api.sightengine.com/1.0/check.json', {
      params: {
        'url': fileUrl,
        'models': 'genai',
        'api_user': API_USER,
        'api_secret': API_SECRET
      }
    });

    const aiScore = Math.round(response.data.type.ai_generated * 100);

    const summary = aiScore > 60 ? text.summaryAI : text.summaryReal;
    const resultMessage = `📊 **${text.title}**\n\n🤖 ${text.aiProb} **${aiScore}%**\n\n${summary}`;

    await bot.sendMessage(chatId, resultMessage, { parse_mode: 'Markdown' }).catch(console.error);

    logToAdmin(msg, 'Video', aiScore, resultMessage);

  } catch (error) {
    console.error('Video tahlilida xatolik:', error);
    const errText = lang === 'en' 
      ? '❌ Sorry, an error occurred while analyzing the video.' 
      : '❌ Kechirasiz, videoni tahlil qilishda xatolik yuz berdi.';
    bot.sendMessage(chatId, errText).catch(console.error);
  }
});